# site settings
title: CS + Social Good
subtitle: at UNC Chapel Hill
email: cssgunc@gmail.com
#description: Fostering discussions and actions for ethical uses of technology, with an aim to give back to UNC and the greater community through our projects and collaborations.
description: Through technology, we have the opportunity to be a part of positive change and evolution of a growing world of possibility. We aim to give nonprofits and organizations for social good in the Chapel Hill area the tools to effectively complete their goals with the use of knowledge and programs.
#baseurl: "/jekyll-website" # the subpath of your site, e.g. /blog
baseurl: "/"
#url: https://unc-cs-sg.github.io # the base hostname & protocol for your site
url: https://cssgunc.org
author:
street_address: Box 205 Frank Porter Graham Student Union, UNC-CH Campus Box 5210
city: Chapel Hill
state: NC
zip_code: 27599
country: United States of America
phone: (919) 590 6000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/cssguncch/
github_url: https://github.com/cssgunc
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
